#Spring properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/question?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: michel9
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    prefix: classpath:/templates
    mode: HTML
        
#Banner properties
banner:
  location: classpath:banner.txt
